export const FORGET_PASSWORD_REQUEST = 'FORGET_PASSWORD_REQUEST';

export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS'

export const FORGET_PASSWORD_FAILED = 'FORGET_PASSWORD_FAILED'

export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST';

export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'

export const LOAD_USER_FAILED = 'LOAD_USER_FAILED'

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'

export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED'

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'

export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED'

export const RESET_ERROR = 'RESET_ERROR'

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'

export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED'

export const LOAD_TARGETS_SUCCESS = 'LOAD_TARGETS_SUCCESS'

export const LOAD_TARGETS_FAILED = 'LOAD_TARGETS_FAILED'

export const LOAD_TARGETS_REQUEST = 'LOAD_TARGETS_REQUEST'

export const SET_TARGET_REQUEST = 'SET_TARGET_REQUEST'
export const SET_TARGET_SUCCESS = 'SET_TARGET_SUCCESS'
export const SET_TARGET_FAILED = 'SET_TARGET_FAILED'

export const CREATE_TARGET_REQUEST = 'CREATE_TARGET_REQUEST'
export const CREATE_TARGET_SUCCESS = 'CREATE_TARGET_SUCCESS'
export const CREATE_TARGET_FAILED = 'CREATE_TARGET_FAILED'

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAILED = 'CREATE_POST_FAILED'

export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST'
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'
export const GET_POSTS_FAILED = 'GET_POSTS_FAILED'
export const GET_USERS_REQUEST = 'GET_USERS_REQUEST'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAILED = 'GET_USERS_FAILED'
export const GET_POST_REQUEST = 'GET_POST_REQUEST'
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS'
export const GET_POST_FAILED = 'GET_POST_FAILED'
export const GET_REPLIES_REQUEST = 'GET_REPLIES_REQUEST'
export const GET_REPLIES_SUCCESS = 'GET_REPLIES_SUCCESS'
export const GET_REPLIES_FAILED = 'GET_REPLIES_FAILED'
export const GET_NOTIFICATIONS_REQUEST = 'GET_NOTIFICATIONS_REQUEST'
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS'
export const GET_NOTIFICATIONS_FAILED = 'GET_NOTIFICATIONS_FAILED'


