export const FORGET_PASSWORD_REQUEST = 'FORGET_PASSWORD_REQUEST';

export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS'

export const FORGET_PASSWORD_FAILED = 'FORGET_PASSWORD_FAILED'

export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST';

export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'

export const LOAD_USER_FAILED = 'LOAD_USER_FAILED'

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'

export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED'

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'

export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED'

export const RESET_ERROR = 'RESET_ERROR'

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'

export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED'


